/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fausto
 */
public class frm_personas extends javax.swing.JPanel {

    /**
     * Creates new form frm_personas
     */
    public frm_personas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp_principal = new javax.swing.JTabbedPane();
        pn_clientes = new javax.swing.JPanel();
        lbl_titulo_clientes = new javax.swing.JLabel();
        lbl_nit = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        lbl_fechadenacimiento = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        spn_scroll = new javax.swing.JScrollPane();
        tbn_clients = new javax.swing.JTable();
        pn_empleado = new javax.swing.JPanel();
        lbl_titulo_empleado = new javax.swing.JLabel();

        lbl_titulo_clientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo_clientes.setForeground(new java.awt.Color(0, 0, 255));
        lbl_titulo_clientes.setText("Formulario Clientes");

        lbl_nit.setText("Nit");

        txt_nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nitActionPerformed(evt);
            }
        });

        lbl_nombre.setText("Nombre");

        lbl_apellido.setText("Apellido");

        lbl_direccion.setText("Direccion");

        lbl_telefono.setText("Telefono");

        lbl_fechadenacimiento.setText("Fecha de nacimiento");

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });

        create.setText("Crear");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        tbn_clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spn_scroll.setViewportView(tbn_clients);

        javax.swing.GroupLayout pn_clientesLayout = new javax.swing.GroupLayout(pn_clientes);
        pn_clientes.setLayout(pn_clientesLayout);
        pn_clientesLayout.setHorizontalGroup(
            pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clientesLayout.createSequentialGroup()
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_clientesLayout.createSequentialGroup()
                        .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_clientesLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lbl_titulo_clientes))
                            .addGroup(pn_clientesLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pn_clientesLayout.createSequentialGroup()
                                        .addComponent(lbl_nit)
                                        .addGap(32, 32, 32)
                                        .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pn_clientesLayout.createSequentialGroup()
                                        .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_nombre)
                                            .addComponent(lbl_apellido)
                                            .addComponent(lbl_direccion)
                                            .addComponent(lbl_telefono))
                                        .addGap(24, 24, 24)
                                        .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_nombre)
                                            .addComponent(txt_apellido)
                                            .addComponent(txt_direccion)
                                            .addComponent(txt_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))
                                    .addGroup(pn_clientesLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lbl_fechadenacimiento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(create)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_clientesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(spn_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_clientesLayout.setVerticalGroup(
            pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clientesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_titulo_clientes)
                .addGap(13, 13, 13)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nit)
                    .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellido)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_fechadenacimiento)
                    .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(create)))
                .addGap(18, 18, 18)
                .addComponent(spn_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tp_principal.addTab("Cliente", pn_clientes);

        lbl_titulo_empleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo_empleado.setForeground(new java.awt.Color(0, 153, 0));
        lbl_titulo_empleado.setText("Formulario");

        javax.swing.GroupLayout pn_empleadoLayout = new javax.swing.GroupLayout(pn_empleado);
        pn_empleado.setLayout(pn_empleadoLayout);
        pn_empleadoLayout.setHorizontalGroup(
            pn_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_empleadoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lbl_titulo_empleado)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        pn_empleadoLayout.setVerticalGroup(
            pn_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_empleadoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_titulo_empleado)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        tp_principal.addTab("Empleado", pn_empleado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tp_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_principal)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nitActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_fechadenacimiento;
    private javax.swing.JLabel lbl_nit;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_titulo_clientes;
    private javax.swing.JLabel lbl_titulo_empleado;
    private javax.swing.JPanel pn_clientes;
    private javax.swing.JPanel pn_empleado;
    private javax.swing.JScrollPane spn_scroll;
    private javax.swing.JTable tbn_clients;
    private javax.swing.JTabbedPane tp_principal;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
